version: 2.0

jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: apt-get install git
      - run: ls -lh

workflows:
  version: 2
  build:
    jobs:
      - build
