version: 2.1

workflows:
  lint:
    jobs:
      lint:
        docker:
          - image: ubuntu/xenial
        steps:
          - checkout
          - run:
              name: "First steps"
              command: >-
                ls -lh
