version: 2.1

workflow:
  lint:
    jobs:
      build:
        docker:
          - image: ubuntu/xenial:latest
        steps:
          - checkout
          - run:
              name: "First steps"
              command: >-
                ls -lh
