version: 2.0

jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - sudo apt-get install git
      - run:
          name: "First steps"
          command: >-
            ls -lh

workflows:
  version: 2
  build:
    jobs:
      - build
