FROM ubuntu:xenial
RUN apt-get update
RUN apt-get install --assume-yes --no-install-recommends apt-utils
RUN apt-get install --assume-yes --no-install-recommends doxygen
RUN apt-get install --assume-yes --no-install-recommends texlive
