---

name: CI
on:
  release:
    type: [created]
  push:
  pull_request:
    branches:
      - master

jobs:
  containers:
    name: Update container images
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: nicolasbock/bml
          tag-sha: true # add git short SHA as Docker tag
      - name: Set up qemu
        uses: docker/setup-qemu-action@v1
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  lint:
    name: Lint sources
    runs-on: ubuntu-latest
    container:
      image: nicolasbock/bml-ci-lint:2
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - run: bundle install
      - run: bundle exec danger || true
      - run: BML_OPENMP=no VERBOSE_MAKEFILE=yes EMACS=emacs26 ./build.sh check_indent

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    needs: lint
    container:
      image: nicolasbock/bml-ci-docs:2
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - run: ./build.sh docs

  docs-test:
    name: Build docs (test)
    runs-on: ubuntu-latest
    needs: lint
    container:
      image: ubuntu:xenial
    steps:
      - run: apt-get update
      - run: apt-get install --assume-yes software-properties-common
      - run: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DBA92F17B25AD78F9F2D9F713DEC686D130FF5E4
      - run: apt-add-repository ppa:janisozaur/cmake-update
      - run: apt-get update
      - run: ln -fs /usr/share/zoneinfo/UTC /etc/localtime
      - run: apt-get install --assume-yes tzdata
      - run: DEBIAN_FRONTEND=noninteractive dpkg-reconfigure --frontend noninteractive tzdata
      - run: |
          apt-get install --assume-yes --no-install-recommends \
          apt-utils \
          build-essential \
          cmake cmake-data \
          doxygen \
          gfortran \
          git-core \
          libblas-dev liblapack-dev \
          openssh-client \
          texlive
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - run: ./build.sh docs
