---

name: CI
on:
  release:
    type: [created]
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: nicolasbock/bml-ci-lint:1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - run: cat /etc/passwd
      - run: cat /etc/os-release
      - run: id
      - run: pwd
      - run: ls -lah
      - run: bundle install
      - run: bundle exec danger || true
      - run: BML_OPENMP=no VERBOSE_MAKEFILE=yes EMACS=emacs26 ./build.sh check_indent
